/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PopoverIndexRouteImport } from './routes/popover/index'
import { Route as rootIndexRouteImport } from './routes/(root)/index'

const PopoverIndexRoute = PopoverIndexRouteImport.update({
  id: '/popover/',
  path: '/popover/',
  getParentRoute: () => rootRouteImport,
} as any)
const rootIndexRoute = rootIndexRouteImport.update({
  id: '/(root)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof rootIndexRoute
  '/popover': typeof PopoverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof rootIndexRoute
  '/popover': typeof PopoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(root)/': typeof rootIndexRoute
  '/popover/': typeof PopoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/popover'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/popover'
  id: '__root__' | '/(root)/' | '/popover/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootIndexRoute: typeof rootIndexRoute
  PopoverIndexRoute: typeof PopoverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/popover/': {
      id: '/popover/'
      path: '/popover'
      fullPath: '/popover'
      preLoaderRoute: typeof PopoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  rootIndexRoute: rootIndexRoute,
  PopoverIndexRoute: PopoverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
